import Vue from 'vue'
import { Button, Form, FormItem, Input, Message, Container, Aside, Main, Header, Row, Menu, Submenu, MenuItem, breadcrumb, BreadcrumbItem, Card, Table, TableColumn, Dialog, Select, Option, Radio, Tree } from 'element-ui'
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Header)
Vue.use(Row)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Dialog)
Vue.use(Select)
Vue.use(Option)
Vue.use(Radio)
Vue.use(Tree)
Vue.prototype.$message = Message
